/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
  };
  globals: {
    'site-settings': SiteSetting;
  };
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Page {
  id: string;
  title?: string;
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  title?: string;
  slug?: string;
  content?: string;
  updatedAt: string;
  createdAt: string;
}
export interface SiteSetting {
  id: string;
  siteTitle?: string;
  navLinks?: string[] | Page[];
  image?: string | Media;
  headerTitle?: string;
  profilePicture?: string | Media;
  name?: string;
  email?: string;
  updatedAt?: string;
  createdAt?: string;
}
