name: deploy payload

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - payload-app/**

env:
  SERVER_URL: https://dashboard.${{ vars.DOMAIN }}

jobs:
  deploy-payload:
    runs-on: ubuntu-latest
    name: build and deploy payload

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: install and build payload
        working-directory: payload-app
        run: npm i && npm run build

      - name: bring containers down
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: docker compose down

      - name: deploy payload folder with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: payload-app
          remote_path: /home/${{ secrets.USER }}/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.KEY }}

      - name: write env variables
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: rm .env && echo SERVER_URL=https://dashboard.${{vars.DOMAIN}} >> .env

      - name: launch docker containers
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: docker compose up -d
